export const theme = {
    colors: {
        primary: '#FF4757',
        primaryLight: '#FF6B81',
        primaryDark: '#FF1E3C',
        secondary: '#FFA502',
        background: '#FFFFFF',
        surface: '#F8F9FA',
        textMain: '#2F3542',
        textMuted: '#747D8C',
        border: '#DFE4EA',
        success: '#2ED573',
        error: '#FF4757',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 40,
    },
    typography: {
        fontFamily: {
            regular: 'System',
            bold: 'System',
        },
        sizes: {
            xs: 12,
            sm: 14,
            md: 16,
            lg: 20,
            xl: 24,
            xxl: 32,
            hero: 48,
        },
        weights: {
            regular: '400' as const,
            medium: '500' as const,
            semibold: '600' as const,
            bold: '700' as const,
            black: '900' as const,
        },
    },
    radii: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        round: 9999,
    },
    shadows: {
        sm: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.05,
            shadowRadius: 4,
            elevation: 2,
        },
        md: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 4,
        },
        lg: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.15,
            shadowRadius: 16,
            elevation: 8,
        },
    },
};
